{
 "title": "Monitor: cardano-node",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{instance=\"localhost:12798\"}"
    }
   ]
  },
  {
   "title": "Mempool bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_mempoolBytes_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Mempool transactions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "TXs processed",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slot",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Processor usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{job=\"prometheus\", mode=\"user\"}[1m]))",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "rts_gc_wall_ms / 1000", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Block",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 17, "w": 9, "x": 3, "y": 20 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[1m])",
     "legendFormat": "{{alias}} {{device}} read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total[1m])",
     "legendFormat": "{{alias}} {{device}} write"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 17, "w": 9, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[1m])*8",
     "legendFormat": "{{alias}} {{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[1m])*8",
     "legendFormat": "{{alias}} {{device}} transmit"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Chain density %",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Key rotation",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_currentKESPeriod_int",
     "legendFormat": "現在のKES"
    },
    {
     "expr": "cardano_node_metrics_operationalCertificateExpiryKESPeriod_int",
     "legendFormat": "KES満了"
    },
    {
     "expr": "(cardano_node_metrics_remainingKESPeriods_int * 1.5)",
     "legendFormat": "KES有効残り日数"
    },
    {
     "expr": "cardano_node_metrics_currentKESPeriod_int - cardano_node_metrics_operationalCertificateStartKESPeriod_int + cardano_node_metrics_remainingKESPeriods_int",
     "legendFormat": "KES整合性"
    }
   ]
  }
 ]
}